[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    paulstoffregen/XPT2046_Touchscreen
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library