[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library